---
- hosts: znuny
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # see https://docs.ansible.com/ansible/latest/user_guide/become.html#risks-of-becoming-an-unprivileged-user
    ansible_common_remote_group: "{{pac}}"
    ansible_remote_tmp: ~/.ansible/tmp

  tasks:
  - name: Create user, domain and database
    import_tasks: tasks/hs_basis.yml

  #################################
  ## create directories
  #################################
  - name: create directory znuny
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/znuny"
      state: directory
  - name: create directory etc
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/etc"
      state: directory
  - name: create directory var/tmp
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/var/tmp"
      state: directory
  - name: create directory var/log
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/var/log"
      state: directory
  - name: create directory var/run
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      path: "/home/pacs/{{pac}}/users/{{user}}/var/run"
      state: directory

  ##################################
  ## install znuny
  ##################################

  - name: install znuny
    become: yes
    become_user: "{{pac}}-{{user}}"
    unarchive:
      src: https://download.znuny.org/releases/znuny-{{znuny_release}}.tar.gz
      remote_src: yes
      dest: /home/pacs/{{pac}}/users/{{user}}/znuny
      extra_opts: [--strip-components=1]
      creates: /home/pacs/{{pac}}/users/{{user}}/znuny/Kernel/Config.pm.dist

  ##################################
  ## configuration
  ##################################

  - name: upload znuny configuration
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/znuny/Kernel/Config.pm" src="templates/Config.pm" mode=0600

  ######################
  ## initialise instance
  ######################

  # TODO

  ########################
  ## setup the apache site
  ########################
  - name: Check for cgi-ssl directory
    become: yes
    become_user: "{{pac}}-{{user}}"
    stat:
      path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/cgi-ssl"
    register: cgissl
  - name: drop cgi-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
       path: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/cgi-ssl"
       state: absent
    when: cgissl.stat.exists and cgissl.stat.isdir
  - name: create symbolic link for cgi-ssl
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/znuny/bin/cgi-bin"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/cgi-ssl"
      state: link

  - name: upload htaccess rewrite rule
    become: yes
    become_user: "{{pac}}-{{user}}"
    template: dest="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl/.htaccess" src="templates/htaccess" mode=0444

  - name: create symbolic link for otrs-web
    become: yes
    become_user: "{{pac}}-{{user}}"
    file:
      src: "/home/pacs/{{pac}}/users/{{user}}/znuny/var/httpd/htdocs"
      dest: "/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/htdocs-ssl/otrs-web"
      state: link

  - name: change read permissions for apache
    become: yes
    become_user: "{{pac}}-{{user}}"
    shell: |
      chmod a+r -R htdocs || exit -1
      # TODO this does not apply yet to cache files that are created after this call!
      #find htdocs -type d -exec chmod o+x {} + || exit -1
      find htdocs -type d -exec chmod g+s {} + || exit -1
      touch /home/pacs/{{pac}}/users/{{user}}/.ansible_read_permission
    args:
      executable: /bin/bash
      chdir: "/home/pacs/{{pac}}/users/{{user}}/znuny/var/httpd"
      creates: "/home/pacs/{{pac}}/users/{{user}}/.ansible_read_permission"

  ####################################
  ## install cron jobs
  ####################################
  - name: enable znuny cronjob
    become: yes
    become_user: "{{pac}}-{{user}}"
    cron:
      name: "znuny cronjob"
      minute: "*/5"
      job: "/home/pacs/{{pac}}/users/{{user}}/znuny/bin/otrs.Daemon.pl start >> /dev/null"
